### ISSUE TITLE
Plugin cannot connect to metadata DB

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#286]
The [`license-feeder` plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-feeder) needs to connect to the metadata DB in order to store license findings.
It implements the `DBConnector` interface:
https://github.com/fasten-project/fasten/blob/59c39caadfab7ca279439dcdc205a8d4dd9f1e3e/analyzer/license-feeder/src/main/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPlugin.java#L30-L31
and overrides the `setDBConnection()` method:
https://github.com/fasten-project/fasten/blob/59c39caadfab7ca279439dcdc205a8d4dd9f1e3e/analyzer/license-feeder/src/main/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPlugin.java#L43-L46

I also set the DB address using the `-d` flag, and its password via the `${FASTEN_DBPASS}` environment variable.

Despite all this, I get the following exception:
```
java.lang.ClassCastException: class org.jooq.impl.DefaultDSLContext cannot be cast to class org.jooq.DSLContext (org.jooq.impl.DefaultDSLContext is in unnamed module of loader 'app'; org.jooq.DSLContext is in unnamed module of loader org.pf4j.PluginClassLoader @4e91d63f)
 	at eu.fasten.analyzer.licensefeeder.LicenseFeederPlugin$LicenseFeeder.setDBConnection(LicenseFeederPlugin.java:45)
 	at eu.fasten.server.FastenServer.lambda$makeDBConnection$12(FastenServer.java:252)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
 	at eu.fasten.server.FastenServer.makeDBConnection(FastenServer.java:250)
	at eu.fasten.server.FastenServer.run(FastenServer.java:200)
 	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
 	at picocli.CommandLine.access$1100(CommandLine.java:145)
 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
 	at picocli.CommandLine.execute(CommandLine.java:2058)
 	at eu.fasten.server.FastenServer.main(FastenServer.java:352)
```

Am I missing something? I followed all the steps described [here](https://github.com/fasten-project/fasten/wiki/Development-Environment#plug-ins-with-db-connection), but no success.

Thank you!

**Comment by marcomicera** [comment]
Assigning this to @mir-am because of [this git blame](https://github.com/fasten-project/fasten/blame/b10b8426a40d6b1590a0d66286b569bebfb6a5c5/server/src/main/java/eu/fasten/server/FastenServer.java#L244-L270).

**Comment by mir-am** [comment]
> Assigning this to @mir-am because of [this git blame](https://github.com/fasten-project/fasten/blame/b10b8426a40d6b1590a0d66286b569bebfb6a5c5/server/src/main/java/eu/fasten/server/FastenServer.java#L244-L270).

What command do you exactly use to run the FASTEN server? You can use a dummy name for DB credentials here.
Also, on what server did you run this?

**Comment by marcomicera** [comment]
> What command do you exactly use to run the FASTEN server?

I'm using

```shell script
docker-compose --profile license-detection up -d
```

in the [`license-detector` branch](https://github.com/fasten-project/fasten-docker-deployment/tree/license-detector) to launch everything.
You won't see the container of the [`license-feeder` plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-feeder) as its CI hasn't built an image yet (integration tests run during the `docker build` fail as Testcontainers cannot pull images).

[This](https://github.com/fasten-project/fasten/blob/59c39caadfab7ca279439dcdc205a8d4dd9f1e3e/docker/license-feeder/Dockerfile#L26) is its entrypoint (or [this](https://github.com/fasten-project/fasten/blob/59c39caadfab7ca279439dcdc205a8d4dd9f1e3e/docker/license-feeder/Dockerfile#L42) when building JARs separately, e.g., locally or in our CI).

> You can use a dummy name for DB credentials here.

Since I'm now using our docker-compose setup, I'm using [these credentials](https://github.com/fasten-project/fasten-docker-deployment/blob/081908ae5474e3183d659ec9454f998fe8449a76/.env#L24-L25).

> Also, on what server did you run this?

On my local machine. I'll move on to Kubernetes once everything works on docker-compose.

**Comment by marcomicera** [comment]
[This integration test](https://github.com/fasten-project/fasten/blob/bd2545ad0aed04cd45814510e0cc1ef07d1c00de/analyzer/license-feeder/src/test/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPluginTest.java#L31-L47) passes, meaning that setting the `${FASTEN_DBPASS}` env var and using the right arguments for `PostgresConnector.getDSLContext()` is indeed enough.
I must be doing something wrong in my `docker-compose.yaml` file...

**Comment by marcomicera** [comment]
> [This integration test](https://github.com/fasten-project/fasten/blob/bd2545ad0aed04cd45814510e0cc1ef07d1c00de/analyzer/license-feeder/src/test/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPluginTest.java#L31-L47) passes, meaning that setting the `${FASTEN_DBPASS}` env var and using the right arguments for `PostgresConnector.getDSLContext()` is indeed enough.

I was debugging this integration test, and the argument of this method

https://github.com/fasten-project/fasten/blob/59c39caadfab7ca279439dcdc205a8d4dd9f1e3e/analyzer/license-feeder/src/main/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPlugin.java#L43-L46

Contains one entry `String` -> `org.jooq.impl.DefaultDSLContext`.
Looks like `org.jooq.impl.DefaultDSLContext` is successfully cast `org.jooq.DSLContext` during the test, but not in my docker-compose environment. Here's again the exception log:

> ```
> java.lang.ClassCastException: class org.jooq.impl.DefaultDSLContext cannot be cast to class org.jooq.DSLContext (org.jooq.impl.DefaultDSLContext is in unnamed module of loader 'app'; org.jooq.DSLContext is in unnamed module of loader org.pf4j.PluginClassLoader @4e91d63f)
>  	at eu.fasten.analyzer.licensefeeder.LicenseFeederPlugin$LicenseFeeder.setDBConnection(LicenseFeederPlugin.java:45)
>  	at eu.fasten.server.FastenServer.lambda$makeDBConnection$12(FastenServer.java:252)
>  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
>  	at eu.fasten.server.FastenServer.makeDBConnection(FastenServer.java:250)
> 	at eu.fasten.server.FastenServer.run(FastenServer.java:200)
>  	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
>  	at picocli.CommandLine.access$1100(CommandLine.java:145)
>  	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
>  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
>  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
>  	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
>  	at picocli.CommandLine.execute(CommandLine.java:2058)
>  	at eu.fasten.server.FastenServer.main(FastenServer.java:352)
> ```

And here's its docker-compose service definition:

```yaml
fasten-license-feeder:
    profiles: ["license-detection", "java", "all"]
    restart: "unless-stopped"
    # image: ${FASTEN_LICENSE_FEEDER_IMAGE}
    build: # only during dev
      context: ../fasten # this being https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin
      dockerfile: docker/license-feeder/Dockerfile
      target: package
    environment:
      FASTEN_DBPASS: "${FASTEN_METADATA_DB_PASSWORD}"
      POD_INSTANCE_ID: "fasten-license-feeder"
    command: [
      "-k", "${KAFKA_INTERNAL_ADDR}",
      "-pl", "LicenseFeeder",
      "-kt", "LicenseFeeder=fasten.LicenseDetector.out",
      "-d",  "mvn=${FASTEN_METADATA_DB_JAVA_URL}",
      "--local_storage"
    ]
    volumes:
      - ${FASTEN_JAVA_VOLUME_MOUNT}
    logging: *default-logging
    depends_on:
      - kafka
      - metadata-db
```
